"""fix

Revision ID: 697f9cc15aea
Revises: 5bc6f09d7d45
Create Date: 2025-08-07 13:56:49.828130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "697f9cc15aea"
down_revision: Union[str, None] = "5bc6f09d7d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("organization_name_key"), "organization", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("organization_name_key"),
        "organization",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
